#!/bin/bash

mkdir -pv work

backup_volume() {
    vol="$1"
    ./vackup export "$vol" "backup/$vol.tar.gz"
}

docker compose stop
backup_volume troop105net_db
backup_volume troop105net_wordpress
docker compose start
