version: '3.1'

services:

  caddy:
    image: caddy:2.7.6-alpine
    environment:
      - SITE_DOMAIN
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./srv:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      front:
      back:

  pet:
    build: ./pet
    networks:
      front:
      back:

  wordpress:
    image: wordpress:6.4.3-php8.2-apache
    restart: always
    depends_on: 
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: define( 'WP_DEBUG_LOG', true );
    volumes:
      - wordpress:/var/www/html
      - ./alias-hosts.sh:/bin/alias-hosts.sh
    secrets:
      - db_password
    networks:
      front:
      back:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - db:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    networks:
      back:

volumes:
  wordpress:
  db:
  caddy_data:
  caddy_config:

networks:
  front:
  back:

secrets:
  db_password:
    file: .db_password
  db_root_password:
    file: .db_root_password
