#!/bin/bash

mkdir -pv work

restore_volume() {
    vol="$1"
    ./vackup import "$vol" "work/$vol.tar.gz"
}

docker compose stop
restore_volume troop105net_db
restore_volume troop105net_wordpress
docker compose start
