FROM ubuntu

RUN apt update && \
    apt upgrade -y

RUN apt install -y \
    net-tools \
    bind9-utils \
    dnsutils \
    python3 \
    zsh \
    vim \
    git \
    curl \
    nmap \
    tcpdump \
    telnet \
    tmux \
    wget

CMD [ "/bin/bash" ]
